version: '3.9'

services:
  fastapi:
    image: ishitasharma14/fastapi:dev  # replace with your actual Docker Hub user ID if needed
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  streamlit:
    image: ishitasharma14/streamlit:dev  # replace with your actual Docker Hub user ID if needed
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      API_URL: http://fastapi:8000
